name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install --force
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        if: always()
        run: npm run lint:js
      - name: linting css
        if: always()
        run: npm run lint:css
      - name: unit testing
        if: always()
        run: npm run test:unit
      - name: build storybook
        if: always()
        run: npm run storybook:build
#        todo: enable after changing loki to chromatic
#      - name: screenshot testing
#        if: always()
#        run: npm run test:ui:ci
